name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies (for Selenium tests)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver google-chrome-stable
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true
      shell: bash

    - name: Set environment variables for Chrome
      run: |
        echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV
        which google-chrome-stable
        google-chrome-stable --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov selenium webdriver-manager

    - name: Run Flask app in background
      run: |
        nohup python app.py & 
        sleep 5  # wait for app to start

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: abdullahbaqai/Continuous_Integration-with-Unit-and-Integration-Tests
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
